### ISSUE TITLE
ikon a userscripthez

### ISSUE THREAD

**Issue by boapps** [Balint66/NeptunSkins#8]
szoval turns out lehet ikont adni userscriptnek, tok meno lenne szerintem
![1641847195_grim](https://user-images.githubusercontent.com/17887448/148836280-d644b5e5-567c-4d14-a0f6-e89ccc6375d0.png)

**Comment by Balint66** [comment]
Egy dev számára nagy segítség lehet egy álmatlan éjszaka.
7b5dbfdfb6dd83639daca4dfd77c1b8f7041b16e
